fastlane/Fastfile
* Basic continuous deployement with Jenkins
* Signing and uploading
=> Fixes Fastline for automatic APKs detection

dat/build.gradle, privacy/build.gradle
dat@cliqz.com -> 0.1.2
privacy@cliqz.com -> 12.43
=> Update extension versions

app/src/main/java/org/mozilla/reference/browser/library/LibraryItemView.kt, app/src/main/java/org/mozilla/reference/browser/library/LibraryPageView.kt, app/src/main/java/org/mozilla/reference/browser/library/history/ui/HistorySearchAdapter.kt, app/src/main/java/org/mozilla/reference/browser/library/history/ui/HistoryView.kt, app/src/main/java/org/mozilla/reference/browser/library/history/ui/HistoryViewModel.kt, app/src/main/java/org/mozilla/reference/browser/library/history/usecases/HistoryUseCases.kt, app/src/main/res/layout/component_history.xml, app/src/main/res/layout/two_line_list_item_layout.xml, app/src/main/res/layout/two_line_list_item_with_action_layout.xml, app/src/main/res/menu/history_menu.xml, app/src/main/res/values/strings.xml
=> NAB-24 add search to history

app/src/main/res/layout/fragment_browser.xml
=> NAB-78 Fresh tab toolbar shouldn't show when app is used as an external browser

Dockerfile, Jenkinsfile
=> Install fastlane locally

app/build.gradle, app/src/androidTest/java/org/mozilla/reference/browser/helpers/ext/String.kt, app/src/main/java/org/mozilla/reference/browser/browser/ToolbarIntegration.kt, app/src/main/java/org/mozilla/reference/browser/database/HistoryDatabase.kt, app/src/main/java/org/mozilla/reference/browser/push/FirebasePush.kt, buildSrc/src/main/java/Dependencies.kt, freshtab/src/main/java/com/cliqz/browser/news/data/source/remote/NewsRemoteDataSource.kt, gradle/wrapper/gradle-wrapper.properties, taskcluster/ci/build-bundle/kind.yml
=> Upgrading gradle version to 5.6.4 and the Android Gradle Plugin to 3.6.0

app/src/androidTest/java/org/mozilla/reference/browser/helpers/MockWebServer.kt, app/src/androidTest/java/org/mozilla/reference/browser/helpers/TestAssetHelper.kt, app/src/androidTest/java/org/mozilla/reference/browser/ui/ThreeDotMenuTest.kt, app/src/androidTest/java/org/mozilla/reference/browser/ui/TopSitesTest.kt, app/src/androidTest/java/org/mozilla/reference/browser/ui/robots/AwesomeBarRobot.kt, app/src/androidTest/java/org/mozilla/reference/browser/ui/robots/FreshTabRobot.kt, app/src/androidTest/java/org/mozilla/reference/browser/ui/robots/NavigationToolbarRobot.kt, app/src/androidTest/java/org/mozilla/reference/browser/ui/robots/ThreeDotMenuRobot.kt, app/src/main/java/org/mozilla/reference/browser/browser/BrowserFragment.kt, app/src/main/java/org/mozilla/reference/browser/browser/FreshTabIntegration.kt, app/src/main/java/org/mozilla/reference/browser/topsites/ui/TopSitesAdapter.kt, app/src/main/java/org/mozilla/reference/browser/topsites/ui/TopSitesFeature.kt, app/src/main/java/org/mozilla/reference/browser/topsites/ui/TopSitesPresenter.kt, app/src/main/java/org/mozilla/reference/browser/topsites/ui/TopSitesView.kt, app/src/main/res/layout/top_site_context_menu.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
=> NAB-86 Add long press new tab/forget tab options for top site

freshtab/src/main/java/com/cliqz/browser/freshtab/FreshTab.kt
=> Freshtab view fixes

buildSrc/src/main/java/com/cliqz/gradle/AssetsDownloader.kt, dat/build.gradle
=> Fixing the extension download task

app/build.gradle, app/metrics.yaml, app/src/main/java/org/mozilla/reference/browser/BrowserApplication.kt, app/src/main/java/org/mozilla/reference/browser/components/Analytics.kt, app/src/main/java/org/mozilla/reference/browser/settings/PrivacySettingsFragment.kt, buildSrc/src/main/java/Dependencies.kt
I'm removing Glean and its support as we will replace Mozilla Telemetry with Anolysis
=> Removing Glean

app/build.gradle, app/src/main/java/org/mozilla/reference/browser/components/Core.kt, app/src/main/java/org/mozilla/reference/browser/library/LibraryItemView.kt, app/src/main/java/org/mozilla/reference/browser/library/LibraryPageView.kt, app/src/main/java/org/mozilla/reference/browser/library/history/ui/viewholders/HistoryItemViewHolder.kt, app/src/main/res/drawable/cliqz_ic_check.xml, app/src/main/res/drawable/divider.xml, app/src/main/res/layout/clear_all_history.xml, app/src/main/res/layout/component_history.xml, app/src/main/res/layout/fragment_history.xml, app/src/main/res/layout/history_list_item.xml, app/src/main/res/layout/top_site_item_layout.xml, app/src/main/res/layout/two_line_list_item_with_action_layout.xml, app/src/main/res/values-notnight/themes.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/mozilla/reference/browser/TestBrowserApplication.kt, app/src/test/java/org/mozilla/reference/browser/assertions/ViewAssertions.kt, app/src/test/java/org/mozilla/reference/browser/ext/Stubber.kt, azure-pipelines.yml, buildSrc/src/main/java/Dependencies.kt, buildSrc/src/main/java/com/cliqz/gradle/AssetsDownloader.kt
=> NAB-15 History design changes

app/src/main/java/org/mozilla/reference/browser/components/ThumbnailsRepository.kt
=> NAB-88-2 registering the session observer when selected too

app/src/androidTest/java/org/mozilla/reference/browser/ui/ExternalIntentsTest.kt, app/src/androidTest/java/org/mozilla/reference/browser/ui/robots/HistoryViewRobot.kt
=> Fixing a couple of automation tests

app/src/main/java/org/mozilla/reference/browser/components/Core.kt, app/src/main/java/org/mozilla/reference/browser/components/UseCases.kt, app/src/main/java/org/mozilla/reference/browser/concepts/HistoryStorage.kt, app/src/main/java/org/mozilla/reference/browser/library/LibraryPageView.kt, app/src/main/java/org/mozilla/reference/browser/library/LibraryToolbar.kt, app/src/main/java/org/mozilla/reference/browser/library/history/ui/HistorySearchAdapter.kt, app/src/main/java/org/mozilla/reference/browser/library/history/ui/HistoryView.kt, app/src/main/java/org/mozilla/reference/browser/library/history/usecases/HistoryUseCases.kt, app/src/main/java/org/mozilla/reference/browser/storage/HistoryDatabase.kt, app/src/main/res/layout/component_history.xml, app/src/main/res/layout/library_toolbar.xml, app/src/main/res/menu/history_menu.xml, app/src/main/res/values/strings.xml, app/src/test/java/org/mozilla/reference/browser/library/history/ui/HistoryFragmentTest.kt, buildSrc/src/main/java/Dependencies.kt, gradle.properties
=> NAB-24 Better History search interface

app/src/main/res/layout/two_line_list_item_layout.xml, app/src/main/res/layout/two_line_list_item_with_action_layout.xml, freshtab/src/main/java/com/cliqz/browser/news/data/source/remote/NewsRemoteDataSource.kt
=> NAB-107 add an outline to the history elements

Dockerfile
=> Adding side by side NDK to the Dockerfile

.gitignore, Jenkinsfile, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/org/mozilla/reference/browser/BrowserApplication.kt, buildSrc/src/main/java/Dependencies.kt, fastlane/Fastfile
=> NAB-43-2 Integrating Sentry version 2.0.2

app/src/main/java/org/mozilla/reference/browser/library/LibraryToolbar.kt, app/src/main/res/color/stateful_tint.xml, app/src/main/res/layout/library_toolbar.xml, app/src/test/java/org/mozilla/reference/browser/assertions/ViewAssertions.kt, app/src/test/java/org/mozilla/reference/browser/library/history/ui/HistoryFragmentTest.kt
=> NAB-24-2 Fix clear search icon color when the query is empty

app/src/main/java/org/mozilla/reference/browser/library/LibraryItemView.kt, app/src/main/java/org/mozilla/reference/browser/library/LibraryToolbar.kt, app/src/main/java/org/mozilla/reference/browser/library/history/ui/HistoryFragment.kt, app/src/main/java/org/mozilla/reference/browser/library/history/ui/HistoryInteractor.kt, app/src/main/java/org/mozilla/reference/browser/library/history/ui/HistoryView.kt, app/src/main/res/menu/history_multi_select_menu.xml, app/src/main/res/values/strings.xml
=> NAB-102 add options to open all the selected history elements

app/src/main/java/org/mozilla/reference/browser/library/history/ui/HistoryFragment.kt, app/src/main/res/values-v23/style.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/style.xml, app/src/test/java/org/mozilla/reference/browser/library/history/ui/HistoryFragmentTest.kt
=> NAB-103 Clear history dialog restyling

README.md, azure-pipelines.yml, build.gradle
=> Fixing JaCoCo tasks

app/src/main/java/org/mozilla/reference/browser/settings/AboutFragment.kt, app/src/main/res/values/strings.xml, extension/build.gradle
Show the version of embedded extensions in settings -> about
=> Display extension versions in 'about' screen

app/build.gradle, app/src/main/java/org/mozilla/reference/browser/addons/AddonsFragment.kt, app/src/main/java/org/mozilla/reference/browser/browser/BaseBrowserFragment.kt, app/src/main/java/org/mozilla/reference/browser/ext/NavController.kt, app/src/main/java/org/mozilla/reference/browser/library/LibraryItemView.kt, app/src/main/java/org/mozilla/reference/browser/settings/PairSettingsFragment.kt, app/src/main/java/org/mozilla/reference/browser/settings/SettingsFragment.kt, buildSrc/src/main/java/Dependencies.kt, buildSrc/src/main/java/com/cliqz/gradle/AssetsDownloader.kt
=> Fixing warnings due to coroutines api and old Kotlin Gradle plugin

app/src/main/res/drawable/history_view_empty_icon.xml, app/src/main/res/layout/component_history.xml, app/src/main/res/values/strings.xml
=> NAB-29 Empty history layout update

app/src/main/java/org/mozilla/reference/browser/library/LibraryItemView.kt, app/src/main/java/org/mozilla/reference/browser/library/history/ui/HistoryFragment.kt, app/src/main/java/org/mozilla/reference/browser/library/history/ui/HistorySearchAdapter.kt, app/src/main/java/org/mozilla/reference/browser/library/history/ui/HistoryView.kt, app/src/test/java/org/mozilla/reference/browser/library/history/ui/HistoryFragmentTest.kt
=> NAB-130 Fixing opening history item after search

app/src/main/java/org/mozilla/reference/browser/browser/ToolbarIntegration.kt
=> NAB-128 transforms the share menu entry to a share icon

dat/build.gradle
=> Update dat extension version

app/src/main/java/org/mozilla/reference/browser/storage/HistoryDatabase.kt
=> NAB-95 trim query string before searching the History

app/src/main/java/org/mozilla/reference/browser/ViewModelFactory.kt, app/src/main/java/org/mozilla/reference/browser/library/history/ui/HistoryFragment.kt, app/src/main/java/org/mozilla/reference/browser/library/history/ui/HistoryViewModel.kt, azure-pipelines.yml
This reverts commit f1ade73fcfa4a024759d16e86b91647d6d38992a.
=> Restoring the ViewModelFactory
